### ISSUE TITLE
Milestone 1 TODO

### ISSUE THREAD

**Issue by Farhan-Faisal** [UBC-MDS/DSCI522-2425-22-wine-chromatic-profile#1]
- [x] - conda lock made and tested
- [x] - Combine notebooks into a report
- [x] - File organization
- [x] - HTML generated
- [x] - Site deployed on Github Pages
- [x] - Release
