### ISSUE TITLE
MS4: Incorporate Milestone 1 Feedback

### ISSUE THREAD

**Issue by Farhan-Faisal** [UBC-MDS/DSCI522-2425-22-wine-chromatic-profile#45]
**MISC**
- [x] Code of Conduct Email (-0.5)
- [x] Fix Data Directory- Raw and Proc Files (-1)
- [x] Add versions for each package in env file (-1)
- [x] References- Regrade Request (-0.25)
- [x] Spelling and Grammer Check (-0.25)
- [x] Github Issues - Regrade request

**ABSTRACT**
- [x] Does not clearly report the major findings. (-0.25)
- [x] Does not discuss importance and limitations of findings. (-0.25)

**INTRODUCTION**
- [x] Did not reference the data set when referring to it. (-0.25)

**DISCUSSION**
- [x] Findings from the project are not linked back to the application domain applied rubric item (-1)
- [x] Assumptions and limitations of methods and findings are not discussed. (-1)

**Comment by adrianl726** [comment]
I think we did reference the dataset no? We just did it in the data section instead of under introduction. Should I just move the data section up and merge it into the introduction to fix this?

**Comment by Farhan-Faisal** [comment]
I think we r good. This went back to milestone 1. We included a link to our dataset but didn’t do an inline citation. I think that’s why they took points off. 

We are properly citing it rn. So don’t think we need changes. Gonna check it off.
