### ISSUE TITLE
MS4: Incorporate Milestone 2 Feedback

### ISSUE THREAD

**Issue by Farhan-Faisal** [UBC-MDS/DSCI522-2425-22-wine-chromatic-profile#51]
**ENVIRONMENT:**
- [x] The Dockefile could be simplified. For instance, multiple RUN instructions could be merged into one. Make Regrade Request. Docker File uses mamba install which does not install pip dependencies. So we need 1 more run statement to install our pip dependencies separately. (-1)
- [x] The platform key and value is missing from the  docker-compose.yml file, causing issues when running on different chip architectures. (-1)

**VALIDATION (-9)**
- [x] We have all 11 validations. Need to make a regrade request

DOCKER IMAGE TAG
- [x] Latest tag was used for docker. This is not ideal because if the user has latest locally, but there is a newer version on the container registry, then Docker will not pull it.
