### ISSUE TITLE
Milestone 2 TODO

### ISSUE THREAD

**Issue by Farhan-Faisal** [UBC-MDS/DSCI522-2425-22-wine-chromatic-profile#6]
- [x] Dockerfile - Farhan
- [x] Docker Compose - Farhan
- [x] docker-publish.yml - Farhan
- [x] Add deepchecks Dependency - Adrian
- [x] Validation Checks 1-4 - Adrian
- [x] Validation Checks 5-8 - Zhiwei
- [x] Validation Checks 9-11 - Daria
- [x] Documentation Changes - Daria
- [x] Release - Zhiwei
